### PR TITLE
Backport Fixes #371 to 4.0.x

### LINKED ISSUE #371: Dev Server: Wrong docs and failing because of monitoring
Hi,

# Wrong docs

```
cd src
pip install -r requirements.txt --upgrade
pip install -e . --upgrade

# Install GDAL Utilities for Python
pip install pygdal=="`gdal-config --version`.*"

# Dev scripts
mv ../.override_dev_env.sample ../.override_dev_env
mv manage_dev.sh.sample manage_dev.sh
mv paver_dev.sh.sample paver_dev.sh

source ../.override_dev_env

# Using the Default Settings
sh ./paver_dev.sh reset
sh ./paver_dev.sh setup
sh ./paver_dev.sh sync
sh ./paver_dev.sh start
```

We're inside `src` and rename the env file one dir higher `mv ../.override_dev_env.sample ../.override_dev_env` but ` ./paver_dev.sh` tries to read the file from the same directory.

https://github.com/GeoNode/geonode-project/blob/3df63509043ce7c90a0b960db852ab82006c2a0b/src/paver_dev.sh.sample#L2

We should correct the path like

```shell
source ../.override_dev_env 
```

# Missing GeoIP

As the geoip database link is currently dead the command for updategeoip fails. Hence I would suggest to disable monitoring.
Which will then disable the command.

https://github.com/GeoNode/geonode-project/blob/3df63509043ce7c90a0b960db852ab82006c2a0b/.env.sample#L195

### PR DESCRIPTION
**Pull request by t-book**
Cherry-picked commits from master.

### CODE REVIEW

File: src/manage_dev.sh.sample [hunk 1]
```diff
@@ -1,3 +1,3 @@
 set -a
-source .override_dev_env
+source ../override_dev_env
```
Comment (afabiani) [inline src/manage_dev.sh.sample]: @t-book  I guess we miss a `.` here?

**Comment by t-book** [comment]
@afabiani Sneaky dot. Strange as I picked both commits. Anyways should be there now.
